### ISSUE TITLE
No unittests

### ISSUE THREAD

**Issue by rboulton** [LinkedInAttic/indextank-engine#10]
There doesn't appear to be a testsuite of any kind associated with this code.  Is this, perhaps, something that got omitted from the open source release?  If so, is there any chance of getting it released too?

If there never was a testsuite, it would be good to start one to allow efficient further development.

**Comment by iperez** [comment]
Because of a license issue we couldn't open source the unit tests yet. But we will get them up here as soon as we can.

**Comment by rboulton** [comment]
Great - glad to hear there are unit tests (!), and good luck with getting them released.

**Comment by iladriano** [comment]
Tests are up.

**Comment by rboulton** [comment]
Great news - thanks.
