### ISSUE TITLE
index bug?

### ISSUE THREAD

**Issue by nghianja** [LinkedInAttic/indextank-engine#15]
Hi all,

I don't know whether you are aware of this but when after I inserted documents into the index 'idx', I can query the same result even if I specify a different index.

e.g.

$ curl http://localhost:20220/v1/indexes/nonidx/search?q=love

will give the same result as in

$ curl http://localhost:20220/v1/indexes/idx/search?q=love

Is this intended?

Thank you.

**Comment by iladriano** [comment]
Yes. The embedded api instantiates a single index always.

**Comment by nghianja** [comment]
I see. Then sorry for asking a stupid question but how do I start the indextank engine such that I can use multiple separate indexes?

**Comment by iladriano** [comment]
Don't worry. Right now, you need to start another process using a different port.

**Comment by nghianja** [comment]
Okay, I understand. Thank you very much once again.
