### ISSUE TITLE
Support for Multiple-Valued Categories

### ISSUE THREAD

**Issue by bencrouse** [LinkedInAttic/indextank-engine#19]
I'd love to see support for multiple category values for a document. This would be great for use cases like tags, multiple colors/sizes on products, etc. I found it surprising that this isn't supported (everything else is so great). It ends up being a show-stopper for me.

**Comment by iladriano** [comment]
+1

**Comment by iperez** [comment]
There was a technical reason for that. 
Take a look at the DynamicDataManager class and its DynamicData subclass. The categories data's representation was meant to optimize resources (keeping the category value for each category for each document in bitmaps). You could implement a work around that but at the cost of having a much larger memory footprint for the same amount of data.
