### ISSUE TITLE
Support fetch/search all document without "q" parameter

### ISSUE THREAD

**Issue by augustine-tran** [LinkedInAttic/indextank-engine#25]
I know that I can add every documents a field "all=1", and then fetch all by indexs/idx/search?q=all:1
But I prefer "q" parameter is a totally optional param.

**Comment by iladriano** [comment]
You're proposing to add a hook that automatically adds the "match all" field to each document and a resource (something like "/search/" with no "q" parameter) that aliases the query matching all documents, right?

My take is that the "?q=all:1" is transparent about what's going on with the index/documents. Also, in some cases the "match all" query might not be needed at all with that overhead still present.

The approach you are proposing is still valid given that queries using other filters (ex.: function filters) may not necessarily require a query conceptually. However, I would like to tailor a proposal that achieves the same without using the "all:1".

+1

**Comment by augustine-tran** [comment]
Thanks adrnai
