### ISSUE TITLE
Why the software history was not kept?

### ISSUE THREAD

**Issue by gustavopinto** [LinkedInAttic/indextank-engine#43]
Hi there,

I'm a researcher studying software evolution. As part of my current research, I'm studying the implications of open-sourcing a proprietary software, for instance, if the project succeed in attracting newcomers. However, I observed that some projects, like indextank-engine, deleted the software history during the transition to open-source.

https://github.com/linkedin/indextank-engine/commit/bbf3a538a2c77efe93c5aceda16f85ccc35c9109

Knowing that software history is indispensable for developers (e.g., developers need to refer to history several times a day), I would like to ask indextank-engine developers the following four brief questions:
1. Why did you decide to not keep the software history?
2. Do the core developers faced any kind of problems, when trying to refer to the old history? If so, how did they solve these problems?
3. Do the newcomers faced any kind of problems, when trying to refer to the old history? If so, how did they solve these problems?
4. How does the lack of history impacted on software evolution? Does it placed any burden in understanding and evolving the software?

Thanks in advance for your collaboration,

Gustavo Pinto, PhD
http://www.gustavopinto.org

**Comment by jhandl** [comment]
Hi Gustavo,

It's been quite some time since we open-sourced IndexTank, and as far as I
know the project didn't evolve much after that as we stopped development
and no community formed around it. Our objective was to help other
companies or individuals to implement the IndexTank service to ensure a
smooth transition of our customers to new providers. That goal was
accomplished. Preserving history was not a priority.

Cheers,
Jorge

**Comment by gustavopinto** [comment]
Thank you, @jhandl!

**Comment by gustavopinto** [comment]
Hi @jhandl, 

thanks once again for answering our research inquiries. We were able to collect 35 responses and we drafted a research paper with the results. The paper was submitted and accepted for the 14th International Conference on Open Source Systems (http://oss2018.org/). You can find the paper [here](http://gustavopinto.org/lost+found/oss2018.pdf). Hope you enjoy reading the paper!

Thanks again,

Gustavo
