### ISSUE TITLE
Problem accessing /v1/indexes/idx/search.

### ISSUE THREAD

**Issue by nghianja** [LinkedInAttic/indextank-engine#8]
Hi all,

I am a web application developer and I am trying out IndexTank to be part of my application. However, I encountered error even when starting with the example.

I followed the given commands:

$ curl -d "{\"docid\":\"post1\", \"fields\":{\"text\":\"I love Fallout\"}}" -v -X PUT http://localhost:20220/v1/indexes/idx/docs

$ curl -d "{\"docid\":\"post2\", \"fields\":{\"text\":\"I love Planescape\"}}" -v -X PUT http://localhost:20220/v1/indexes/idx/docs

$ curl http://localhost:20220/v1/indexes/idx/search?q=love

Then the search returned the following error,

java.lang.Error: Unresolved compilation:
at com.flaptor.util.CollectionsUtil.mergeIterables(CollectionsUtil.java:186)

Could it be a problem with java type erasure as indicated by eclipse when I imported the source code in?

Please advise on what I should do to rectify the problem. Thank you very much in advance.

**Comment by iladriano** [comment]
dated eclipse perhaps?

**Comment by nghianja** [comment]
I am using Eclipse Helios and I have always kept it updated. What is the version you are using?

Anyway, I didn't use it for compilation but followed the instructions and ran the maven build. Anything I could have missed?

**Comment by iladriano** [comment]
Currently, I'm using eclipse "indigo":

Eclipse IDE for Java Developers
Version: Indigo Service Release 1
Build id: 20110916-0149

Do you have more details about the "Unresolved compilation" error?

I'll try to reproduce the error, which java, maven and os versions are you working with?

**Comment by nghianja** [comment]
I don't have much info. I encountered this on both Mac and Linux.

OS: Mac Snow Leopard and Turnkey Linux
Java: Java 1.6.0_29 (Mac) and Open JDK (Linux)
Maven: Mac in-built and Maven2 (Linux)

**Comment by iladriano** [comment]
I've merged a pull request with Open JDK compilation issues solved. Please give it a try.

**Comment by nghianja** [comment]
Oh thank you very much, especially replying to my question over the new year weekend! I have tested it on both Mac and Linux and it works.
